package com.dev.nguyenvantung.fg_app.utils;

public class AppConstants {
    public static final String END_POINT = "http://10.204.204.84/Laravel/FG-YouthUnion/public/api/v1/";

    public static final String TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImVhNDQ1ZmU4NjRlODBjNTg0NzFlMjA3NDFkMTFlOTQ0Yjk5Y2I3YTUyYWJmMTgyOWQ3MWIwY2ZhOTM0NmY0ZmQ5ZjQ0OGE2NWIxMmY0Mzc5In0.eyJhdWQiOiIxIiwianRpIjoiZWE0NDVmZTg2NGU4MGM1ODQ3MWUyMDc0MWQxMWU5NDRiOTljYjdhNTJhYmYxODI5ZDcxYjBjZmE5MzQ2ZjRmZDlmNDQ4YTY1YjEyZjQzNzkiLCJpYXQiOjE1MzkzOTE3ODYsIm5iZiI6MTUzOTM5MTc4NiwiZXhwIjoxNTcwOTI3Nzg2LCJzdWIiOiIyIiwic2NvcGVzIjpbXX0.ZFBdxouViYcq0cM4Ro5FEN_c2heJk22LwYV0jc7XMn1NdFlhUH_iXF4onoPb2E-dwLqzfxhU3QqT8fhk0KKxdMygXX9dKcuILX87laPOlc2_K3aYaLqmYsjbQQ-OPCxqClpKEBveJ9aHsDl-pnieDgkZDRoIfZh1gOTBbkBSrp1USNxzB5yucOKo7k0Byva45z4OYDgOnsrF5Mx1ftahVoyNJaYII40NlDDgDnZFR8loAxbhAx_Fb1tDyJKjkFlwxTGGlJJbZjD6PgVnc_HJBuoFmeyXfsu5MeHvHc0LvGp4IemneUci058dPoaRbX-AxK9SH5ySIB1GS9f5sKRLUZt_tgpVpW2CyREBSDjXETG3KDQMMoSra_yCn3m3WUl8xR5iHfvq-Ma54QwHqtxBF2sAwagdWxUHSY3M20oOcZUMFDghk4VmSqBJYrmkXtZkjMamannM_jqguZ0Aisl6HdwVupW5074j2zEIFR1KSBt9NKxvDwfwbnPO3ARoxqgsOXMjKYztZUS_19kJZJI9aXIm_2wdHi2tQESXz-cPdcULJ9ZlFxhH8fKRS21Kpbh7bQZZZibePON392fAGUvxSeI5nR4Tg1QecifRBwx6JuzUjrsgWNTsFOYF17xJ7z3XIP0umR2-2wJdXDrcItCur7yjVp-voWTbPa_RnyN0nPQ";

    public static final String API_TOKEN = "apitoken";
    public static final String BEARER = "Bearer ";
    public static final String AUTHORIZATION = "Authorization";

    public static final String APP_PREF = "App_pref";
}
